export const DEFAULT_EXPENSE_CATEGORIES = [
    "Rent",
    "Mortgage",
    "Property Tax",
    "Home Insurance",
    "Maintenance & Repairs",
    "Electricity",
    "Water",
    "Gas",
    "Internet",
    "Cable TV",
    "Waste Disposal",
    "Groceries",
    "Dining Out",
    "Snacks",
    "Fuel",
    "Public Transport",
    "Ride Hailing",
    "Car Payment",
    "Car Insurance",
    "Vehicle Maintenance",
    "Parking",
    "Tolls",
    "Medical Bills",
    "Health Insurance",
    "Dental Care",
    "Vision Care",
    "Medications",
    "Fitness / Gym",
    "Clothing",
    "Personal Care",
    "Haircuts",
    "Cosmetics",
    "Laundry",
    "Tuition",
    "Books",
    "Courses",
    "Certifications",
    "Workshops",
    "Office Supplies",
    "Software Subscriptions",
    "Internet (Work)",
    "Phone (Work)",
    "Equipment",
    "Coworking Space",
    "Movies",
    "Streaming Services",
    "Games",
    "Events",
    "Hobbies",
    "Loan Repayment",
    "Credit Card Payment",
    "Savings",
    "Investments",
    "Bank Fees",
    "Childcare",
    "School Fees",
    "Allowance",
    "Gifts",
    "Flights",
    "Accommodation",
    "Local Transport",
    "Travel Insurance",
    "Donations",
    "Charity",
    "Religious Contributions",
    "Emergency Expenses",
    "Misc.",
  ];